# Netlify configuration file

# Default build settings
[build]
  # Directory to publish (relative to root of your repo)
  publish = "dist"
  # Default build command
  command = "npm run build"

# Handle SPA routing (redirects all requests to index.html)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Example environment variables for different environments 
# You should set these in the Netlify dashboard instead
# [context.production.environment]
#   VITE_BACKEND_URL = "https://your-production-backend.com"

# [context.deploy-preview.environment]
#   VITE_BACKEND_URL = "https://your-staging-backend.com"

# Cache control for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 