# Netlify configuration file

# Default build settings
[build]
  # Directory to publish (relative to root of your repo)
  publish = "dist"
  # Default build command
  command = "npm run build"

# Handle SPA routing (redirects all requests to index.html)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Example environment variables for different environments 
# You should set these in the Netlify dashboard instead
# [context.production.environment]
#   VITE_BACKEND_URL = "https://your-production-backend.com"

# [context.deploy-preview.environment]
#   VITE_BACKEND_URL = "https://your-staging-backend.com"

# Cache control for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Force browsers to get fresh PWA icon files
[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Force browsers to get fresh manifest files
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Force browsers to get fresh service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0" 